# Generated by Django 3.2.9 on 2021-12-21 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
