# Generated by Django 3.2.9 on 2021-12-22 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_song_play_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='song',
            name='status',
        ),
        migrations.RemoveField(
            model_name='songsuggestion',
            name='album_art',
        ),
        migrations.RemoveField(
            model_name='songsuggestion',
            name='artist_name',
        ),
        migrations.RemoveField(
            model_name='songsuggestion',
            name='song_title',
        ),
        migrations.RemoveField(
            model_name='songsuggestion',
            name='song_url',
        ),
        migrations.RemoveField(
            model_name='songsuggestion',
            name='status',
        ),
        migrations.AddField(
            model_name='songsuggestion',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songsuggestion',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.song'),
            preserve_default=False,
        ),
    ]
