# Generated by Django 3.2.9 on 2021-12-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20211222_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='apple_song_id',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
