# Generated by Django 3.2.9 on 2021-12-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_device_device_name'),
        ('events', '0007_auto_20211224_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(editable=False, to='accounts.PartyGuest'),
        ),
    ]
