# Generated by Django 3.2.9 on 2021-12-24 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_device_device_name'),
        ('events', '0008_alter_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='suggestion_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='songsuggestion',
            name='suggested_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.partyguest'),
            preserve_default=False,
        ),
    ]
