# Generated by Django 3.2.9 on 2021-12-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20211227_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='songsuggestion',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
