# Generated by Django 3.2.9 on 2022-01-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_songsuggestion_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
