# Generated by Django 3.2.9 on 2022-01-04 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211229_1136'),
        ('events', '0012_event_event_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='songsuggestion',
            name='suggesters',
            field=models.ManyToManyField(editable=False, related_name='suggesters', to='accounts.PartyGuest'),
        ),
        migrations.AlterField(
            model_name='songsuggestion',
            name='suggested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_by', to='accounts.partyguest'),
        ),
    ]
