# Generated by Django 3.2.9 on 2022-01-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20220104_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event_images/party_people_3.png', upload_to='event_images'),
        ),
    ]
