# Generated by Django 3.2.9 on 2022-01-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_eventorganizer_profile_photo'),
        ('events', '0014_alter_event_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='songsuggestion',
            name='suggested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_by', to='accounts.partyguest'),
        ),
    ]
