# Generated by Django 3.2.9 on 2021-12-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_id',
            field=models.CharField(default='party', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='device', max_length=60),
            preserve_default=False,
        ),
    ]
