# Generated by Django 3.2.9 on 2021-12-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211217_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorganizer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo'),
        ),
        migrations.AddField(
            model_name='partyguest',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo'),
        ),
    ]
