# Generated by Django 3.2.9 on 2021-12-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211217_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
