# Generated by Django 3.2.9 on 2021-12-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_device_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(default='android', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='registration_id',
            field=models.CharField(default='sdfds', max_length=256),
            preserve_default=False,
        ),
    ]
