# Generated by Django 3.2.9 on 2022-01-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211229_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorganizer',
            name='social_profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
