# Generated by Django 3.2.9 on 2022-01-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_eventorganizer_social_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='show_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='devices',
            field=models.ManyToManyField(editable=False, to='accounts.Device'),
        ),
        migrations.AlterField(
            model_name='eventorganizer',
            name='profile_photo',
            field=models.ImageField(blank=True, default='organizer-profile-icon.png', null=True, upload_to='profile_photo'),
        ),
        migrations.AlterField(
            model_name='partyguest',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photo/avatar_upload.png', null=True, upload_to='profile_photo'),
        ),
    ]
