# Generated by Django 3.2.9 on 2022-01-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220107_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='registration_id',
            new_name='fcm_id',
        ),
    ]
