# Generated by Django 3.2.9 on 2022-01-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_registration_id_device_fcm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizer',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photo/organizer-profile-icon.png', null=True, upload_to='profile_photo'),
        ),
    ]
