# Generated by Django 3.2.9 on 2022-08-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_accountdeleterequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdeleterequest',
            old_name='code',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='accountdeleterequest',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountdeleterequest',
            name='confirmed',
            field=models.BooleanField(null=True),
        ),
        migrations.RemoveField(
            model_name='accountdeleterequest',
            name='device',
        ),
        migrations.AddField(
            model_name='accountdeleterequest',
            name='device',
            field=models.ManyToManyField(to='accounts.Device'),
        ),
    ]
