# Generated by Django 3.2.9 on 2022-08-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20220822_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdeleterequest',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
